---

- name: Logstash Daemon Configuration
  template:
    src:   etc/logstash/logstash.yml.j2
    dest:  "{{logstash_conf_prefix}}/logstash.yml"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode:  "0644"
  notify: logstash restart

- name: Logstash JVM options
  template:
    src:   etc/logstash/jvm.options.j2
    dest:  "{{logstash_conf_prefix}}/jvm.options"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode:  "0644"
  notify: logstash restart

- name: Log4j2 properties
  template:
    src:   etc/logstash/log4j2.properties.j2
    dest:  "{{logstash_conf_prefix}}/log4j2.properties"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_log4j2_properties

- name: Logstash Input config
  template:
    src:   etc/logstash/conf.d/input.conf.j2
    dest:  "{{logstash_conf_dir}}/input.conf"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_input

- name: Logstash Filter config
  template:
    src:   etc/logstash/conf.d/filters.conf.j2
    dest:  "{{logstash_conf_dir}}/filters.conf"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_filter

- name: Logstash Output config
  template:
    src:  etc/logstash/conf.d/output.conf.j2
    dest: "{{logstash_conf_dir}}/output.conf"
    owner: "{{ logstash_owner }}"
    group: "root"
    mode: "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_output

# vi:ts=2:sw=2:et:ft=yaml
